version: 2

builds:
  - env:
    - CGO_ENABLED=1
    main: .
    goos:
      - linux
    goarch:
      - amd64
    binary: mango-go
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}
    hooks:
      pre: make assets

archives:
  - formats: ['tar.gz']
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
    allow_different_binary_count: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  use: github-native

release:
  draft: false
  prerelease: false
  name_template: '{{ .ProjectName }} {{ .Version }}'
  header: |
    ## Mango v{{.Version}}

    A self-hosted manga server and web reader written in Go.


    ### Installation

    Download the appropriate binary for your platform below.

  footer: |
    **Full Changelog**: https://github.com/vrsandeep/mango-go/compare/{{.PreviousTag}}...{{.Tag}}
