services:
  mango:
    build: .
    container_name: mango-go
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      # Override the database and library paths to point to the mounted volumes.
      - MANGO_DATABASE_PATH=/app/data/mango.db
      - MANGO_LIBRARY_PATH=/manga # optional
      # You can also override the port, e.g.,
      # - MANGO_PORT=8080
    user: "1000:1000"
    volumes:
      # This will store the SQLite database and any other app data.
      - ./data:/app/data
      # Mount your actual manga library on your host machine to /manga inside the container.
      - ./manga:/manga

networks:
  default:
    name: mango-network