name: GitHub Actions Release

on:
  push:
    branches:
      - feat/release-workflow

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libsqlite3-dev make gcc

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install esbuild
        run: npm install -g esbuild

      - name: Build assets
        run: make assets

      - name: Build binary
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} CGO_ENABLED=1 go build \
            -ldflags="-s -w -X main.version=${{ github.ref_name }} -X main.commit=${{ github.sha }} -X main.date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            -o mango-go-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }} \
            .

      - name: Create release archive
        run: |
          tar -czf mango-go-${{ matrix.os }}-${{ matrix.arch }}.tar.gz \
            mango-go-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }} \
            README.md LICENSE config.yml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mango-go-${{ matrix.os }}-${{ matrix.arch }}
          path: mango-go-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create checksums
        run: |
          cd mango-go-linux-amd64
          sha256sum *.tar.gz > checksums.txt
          cd ../mango-go-linux-arm64
          sha256sum *.tar.gz >> checksums.txt
          cd ../mango-go-linux-386
          sha256sum *.tar.gz >> checksums.txt
          cd ../mango-go-darwin-amd64
          sha256sum *.tar.gz >> checksums.txt
          cd ../mango-go-darwin-arm64
          sha256sum *.tar.gz >> checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/*.tar.gz
            **/checksums.txt
          generate_release_notes: true
          draft: true
          prerelease: true
