name: Tagged Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a GitHub release
      packages: write # Required to publish Docker images to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev make gcc

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install esbuild
        run: npm install -g esbuild

      - name: Build release binaries
        run: make release-assets

      - name: Create release archives
        run: |
          tar -czvf build/mango-go-linux-amd64.tar.gz build/mango-go-linux-amd64 README.md LICENSE
          tar -czvf build/mango-go-macos-amd64.tar.gz build/mango-go-macos-amd64 README.md LICENSE
          tar -czvf build/mango-go-macos-arm64.tar.gz build/mango-go-macos-arm64 README.md LICENSE

      - name: Upload release binaries
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: build/*.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4

      - name: Download release assets
        uses: actions/download-artifact@v4
        with:
          name: release-assets
          path: build/*.tar.gz

      - name: Create checksums
        run: |
          sha256sum build/mango-go-linux-amd64.tar.gz > build/mango-go-linux-amd64.checksum.txt
          sha256sum build/mango-go-macos-amd64.tar.gz > build/mango-go-macos-amd64.checksum.txt
          sha256sum build/mango-go-macos-arm64.tar.gz > build/mango-go-macos-arm64.checksum.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # This will upload all files from the './build' directory
          # that were created in the Makefile.
          files: |
            ./build/mango-go-linux-amd64.tar.gz
            ./build/mango-go-macos-amd64.tar.gz
            ./build/mango-go-macos-arm64.tar.gz
            ./build/mango-go-linux-amd64.checksum.txt
            ./build/mango-go-macos-amd64.checksum.txt
            ./build/mango-go-macos-arm64.checksum.txt
          # This will automatically generate release notes from your commits
          generate_release_notes: true
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
