name: Run Tests

on:
  # Triggers the workflow on push events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libsqlite3-dev npm make && \
          npm install -g esbuild

      - name: Build assets and download Go dependencies
        run: make assets download-go-deps

      - name: Run tests
        run: go test ./...
